### ISSUE TITLE
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"

### ISSUE THREAD

**Issue by Zash** [wahern/cqueues#176] opened 2017-01-13 15:16 UTC
I saw this warning while installing https://luarocks.org/cqueues-20161215.52-0.src.rock

```
In file included from /usr/include/limits.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:168,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h:34,
                 from /tmp/luarocks_cqueues-20161215.52-0-w3oYFw/cqueues-rel-20161215/src/lib/dns.c:41:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
```

This is on Debian Stretch aka testing

```
gcc: 4:6.2.1-1
libc6-dev: 2.24-8
```

**Comment by daurnimator** [comment] 2017-01-14 00:53
Duplicate of #4

**Closed by daurnimator** 2017-01-14 00:53 UTC
Labels: duplicate
