### ISSUE TITLE
Error with `SSLv3_server_method` with rock version 20150907

### ISSUE THREAD

**Issue by ChickenNuggers** [wahern/cqueues#135] opened 2016-02-01 20:06 UTC
```
/tmp/luarocks_cqueues-20150907.52-0-5359/cqueues-rel-20150907/src/lib/socket.c: In function ‘so_starttls’:
/tmp/luarocks_cqueues-20150907.52-0-5359/cqueues-rel-20150907/src/lib/socket.c:2092:53: warning: implicit declaration of function ‘SSLv3_server_method’ [-Wimplicit-function-declaration]
  if (!method->ssl_connect || method->ssl_connect == SSLv3_server_method()->ssl_connect)
                                                     ^
/tmp/luarocks_cqueues-20150907.52-0-5359/cqueues-rel-20150907/src/lib/socket.c:2092:74: error: invalid type argument of ‘->’ (have ‘int’)
  if (!method->ssl_connect || method->ssl_connect == SSLv3_server_method()->ssl_connect)
                                                                          ^
make: *** [/tmp/luarocks_cqueues-20150907.52-0-5359/cqueues-rel-20150907/src/lib/socket.o] Error 1

Error: Build error: Failed building.
```

**Comment by daurnimator** [comment] 2016-02-02 01:15
Duplicate of #113

**Closed by daurnimator** 2016-02-02 01:15 UTC
