### ISSUE TITLE
AF_UNIX can't bind source and destination

### ISSUE THREAD

**Issue by kcsoft** [wahern/cqueues#194] opened 2017-11-16 17:56 UTC
I'm trying to implement a similar function with cqueues socket:
Complete source can be found [here](http://w1.fi/hostapd/devel/wpa__ctrl_8c_source.html)

```lua

00063 struct wpa_ctrl * wpa_ctrl_open(const char *ctrl_path)
00064 {
00065         struct wpa_ctrl *ctrl;
00066         static int counter = 0;
00067         int ret;
00068         size_t res;
00069         int tries = 0;
00070 
00071         ctrl = os_malloc(sizeof(*ctrl));
00072         if (ctrl == NULL)
00073                 return NULL;
00074         os_memset(ctrl, 0, sizeof(*ctrl));
00075 
00076         ctrl->s = socket(PF_UNIX, SOCK_DGRAM, 0);
00077         if (ctrl->s < 0) {
00078                 os_free(ctrl);
00079                 return NULL;
00080         }
00081 
00082         ctrl->local.sun_family = AF_UNIX;
00083         counter++;
00084 try_again:
00085         ret = os_snprintf(ctrl->local.sun_path, sizeof(ctrl->local.sun_path),
00086                           "/tmp/wpa_ctrl_%d-%d", getpid(), counter);
00087         if (ret < 0 || (size_t) ret >= sizeof(ctrl->local.sun_path)) {
00088                 close(ctrl->s);
00089                 os_free(ctrl);
00090                 return NULL;
00091         }
00092         tries++;
00093         if (bind(ctrl->s, (struct sockaddr *) &ctrl->local,
00094                     sizeof(ctrl->local)) < 0) {
00095                 if (errno == EADDRINUSE && tries < 2) {
00096                         /*
00097                          * getpid() returns unique identifier for this instance
00098                          * of wpa_ctrl, so the existing socket file must have
00099                          * been left by unclean termination of an earlier run.
00100                          * Remove the file and try again.
00101                          */
00102                         unlink(ctrl->local.sun_path);
00103                         goto try_again;
00104                 }
00105                 close(ctrl->s);
00106                 os_free(ctrl);
00107                 return NULL;
00108         }
00109 
00110         ctrl->dest.sun_family = AF_UNIX;
00111         res = os_strlcpy(ctrl->dest.sun_path, ctrl_path,
00112                          sizeof(ctrl->dest.sun_path));
00113         if (res >= sizeof(ctrl->dest.sun_path)) {
00114                 close(ctrl->s);
00115                 os_free(ctrl);
00116                 return NULL;
00117         }
00118         if (connect(ctrl->s, (struct sockaddr *) &ctrl->dest,
00119                     sizeof(ctrl->dest)) < 0) {
00120                 close(ctrl->s);
00121                 unlink(ctrl->local.sun_path);
00122                 os_free(ctrl);
00123                 return NULL;
00124         }
00125 
00126         return ctrl;
00127 }

```

I can't see any way to bind the source and destination like on line 00093 and connect like 00118. Is there a way to implement this with cqueues?

**Comment by daurnimator** [comment] 2017-11-16 23:13
Seems easy enough to add the feature. Will send in PR soon.

**Comment by daurnimator** [comment] 2017-11-17 03:03
Let me know if #195 works for your usecase.

**Comment by kcsoft** [comment] 2017-11-17 16:22
Thank you for your quick reaction.

I have compiled with #195 and managed to make a small test app. Everything seems to work just fine. I was able to send and receive data.

**Comment by daurnimator** [comment] 2017-11-20 02:53
I'm left wondering what the `bind` in your code sample achieves: it's using a temporary path, and retrying on failure. Is there something else out there that is doing some sort of auth via checking `peername`?

**Comment by kcsoft** [comment] 2017-12-13 14:24
Not as far as I know. You can find the link to the complete source in the fist comment

**Comment by daurnimator** [comment] 2017-12-18 07:12
> Not as far as I know. You can find the link to the complete source in the fist comment

I know: but I'm wondering what the issue is if you *don't* do the bind: I'm not clear why it would need to happen at all.

**Comment by kcsoft** [comment] 2018-01-08 14:41
Without the bind it doesn't communicate. I think one is used for input and one for output.

**Comment by daurnimator** [comment] 2019-07-21 03:02
#195 is now merged.

**Closed by daurnimator** 2019-07-21 03:02 UTC
Labels: component: socket, enhancement
