### ISSUE TITLE
luarocks install failed

### ISSUE THREAD

**Issue by MistShi** [wahern/cqueues#129] opened 2015-12-30 08:09 UTC
Installing https://luarocks.org/cqueues-20150907.53-0.src.rock...
Using https://luarocks.org/cqueues-20150907.53-0.src.rock... switching to 'build' mode
/private/tmp/luarocks_cqueues-20150907.53-0-3856/cqueues-rel-20150907/mk/vendor.cc: line 7: export: `-E': not a valid identifier
/private/tmp/luarocks_cqueues-20150907.53-0-3856/cqueues-rel-20150907/mk/vendor.cc: line 7: export: `-': not a valid identifier
luapath: export MACOSX_DEPLOYMENT_TARGET=10.8; gcc: command not found
luapath: export MACOSX_DEPLOYMENT_TARGET=10.8; gcc: command not found
luapath: export MACOSX_DEPLOYMENT_TARGET=10.8; gcc: command not found
Unable to find Lua 5.3 API headers (CPPFLAGS=)
make: *** [/private/tmp/luarocks_cqueues-20150907.53-0-3856/cqueues-rel-20150907/src/5.3/cqueues.o] Error 1

**Comment by daurnimator** [comment] 2015-12-30 08:13
Duplicate of #46.
Fixed in luarocks 2.3.0.
Workaround is to pass `CC=gcc` on the luarocks command line

**Closed** 2015-12-30 09:39 UTC
Labels: duplicate, packaging/portability
