### ISSUE TITLE
thread:join hangs if thread is killed.

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#51] opened 2015-01-27 05:00 UTC
If a thread gets killed in certain ways, `:join` hangs

In the below example I use secure computing mode (via [ljsyscall](https://github.com/justincormack/ljsyscall)), which will make it so that the thread is killed when it uses a syscall besides `read`, `write`, `_exit`, `sigreturn`
```lua
local ct = require "cqueues.thread"
local thread = ct.start(function(sock)
    local syscall = require "syscall"
    syscall.prctl("SET_SECCOMP", 1)
    syscall.sleep(1) -- something not allowed by seccomp, we'll get killed
end)
print(thread:join()) -- never returns
```

**Comment by wahern** [comment] 2015-02-19 02:09
Can you try the branch 51-join-defunct-thread? You'll need to define HAVE_PTHREAD_MUTEX_ROBUST in CPPFLAGS.

Unfortunately, there's no way to be notified if a thread is killed, not even as some kind of Linux extension. However, using POSIX robust mutexes we can periodically check if a thread is gone. The final solution will require that ct:join wake up every N seconds to attempt to join, at which time we can check to see if the thread is gone.

Only Linux and Solaris seem to support robust mutexes. POSIX doesn't guarantee a robust mutex will return EOWNERDEAD if a thread exits, only if a process exits. But fortunately both Linux and Solaris seem to implement this optional behavior.

If the patch works I'll add some code to detect at compile-time if robust mutexes are provided.

**Comment by daurnimator** [comment] 2015-02-19 19:35
> Can you try the branch 51-join-defunct-thread? You'll need to define HAVE_PTHREAD_MUTEX_ROBUST in CPPFLAGS.

Didn't seem to fix the issue.

> Unfortunately, there's no way to be notified if a thread is killed, not even as some kind of Linux extension.

What about `SIGCHLD`? or is that not fired for LWPs?

> However, using POSIX robust mutexes we can periodically check if a thread is gone.
> Only Linux and Solaris seem to support robust mutexes.

What about `waitid` instead?

**Comment by wahern** [comment] 2015-02-20 01:46
The current branch is an incomplete fix. You still need to pass a timeout to ct:join. See the unit test in regress/51-join-defunct-thread.

The unit test uses pthread_exit and I need to confirm that pthread_exit isn't doing something fancy; that the thread being killed asynchronously by the kernel will still cause the robust mutex to be updated properly.

**Comment by daurnimator** [comment] 2015-02-20 16:44
> The current branch is an incomplete fix. You still need to pass a timeout to ct:join.

I'm not sure what difference I'm supposed to observe?
It works without the patch if I pass a timeout....

**Comment by wahern** [comment] 2015-02-21 02:40
See the regression test for the difference. If the timeout expires, you should get an ETIMEDOUT error. If the robust mutex successfully detects that the thread died, you should get an EOWNERDEAD error.

You can just try hacking the regress/51-join-defunct-thread unit test. Just replace the call to pthread_exit with your ljsyscall seccomp code. I figured it would be easier for you to test since you already have that module installed, and I don't [yet] have a luarocks installation setup on a Linux box.

Or is there a Debian module for ljsyscall?

**Comment by daurnimator** [comment] 2015-02-21 05:16
> See the regression test for the difference. If the timeout expires, you should get an ETIMEDOUT error. If the robust mutex successfully detects that the thread died, you should get an EOWNERDEAD error.

I'm seeing some odd results.
With the example in first post (but with sleep changed to 2 seconds so the `:join` finishes first); I always see errno = 110 (with or without the prctl).

However, if I swap `sleep` for `print`; it still hangs forever, even with `:join(0)`!
End of strace:
```
[pid  8005] prctl(PR_SET_SECCOMP, 0x1, 0, 0, 0) = 0
[pid  8005] +++ killed by SIGKILL +++
<... epoll_wait resumed> {}, 32, 999)   = 0
epoll_ctl(7, EPOLL_CTL_DEL, 3, 7fff61f09e30) = 0
read(3, 0x7fff61f09fcf, 1)              = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f03ce1e0970, FUTEX_WAIT_PRIVATE, 2, NULL
```

**Comment by daurnimator** [comment] 2015-02-21 06:51
o.o and I just found out. the process *never* quits.
I just looked at htop for other reasons, and all the tests I did are still running!
(just killed them)

**Comment by wahern** [comment] 2015-06-02 17:40
Can you run the 51-join-defunct-thread.lua regression test? Just do `cd regress && ./51-join-defunct-thread.lua.` This issue should already be fixed as well as it reasonably can be.

**Comment by daurnimator** [comment] 2015-06-03 01:35
I see:
```
$ ./51-join-defunct-thread.lua 
51-join-defunct-thread.lua: calling prctl(PR_SET_SECCOMP, SECCOMP_MODE_STRICT)
51-join-defunct-thread.lua: attempting to open /nonexistant
51-join-defunct-thread.lua: robust mutex strategy not supported on this system
```

on my linux system

**Comment by wahern** [comment] 2015-06-03 02:47
D'oh. I forgot that I need autoconf to be able to set HAVE_PTHREAD_MUTEX_ROBUST. Unfortunately PTHREAD_MUTEX_ROBUST is only an enum for glibc, and not a preprocessor define.

**Comment by wahern** [comment] 2015-08-10 23:03
On Alpine Linux, which uses musl-libc, the regression test for this bug always hung. It turns out that the thread was killed when it wrote to stderr and after it had called flockfile, causing the main thread to block forever in flockfile when attempting to write to stderr. (I fixed the test case by redirecting log messages over a cqueues socket.)

I don't think there is really any safe way to handle an asynchronous cancellation in a generic manner, and _especially_ a real asynchronous termination by the kernel as in this case---the kernel wouldn't obey our POSIX pthread cancellation policy.

I think once I get the autoconf stuff in (which will detect and enable support for PTHREAD_MUTEX_ROBUST), this ticket should get closed. At the end of the day, as the musl-libc case shows, there's simply no way to prevent a deadlock in all possible cases, which means that this ticket could never be closed if the goal was to never hang when joining an asynchronously cancelled thread.

At best we can try to identify areas where we end up with inconsistent state when POSIX deferred cancellations are enabled. But by-and-large that should already be the case because we need to be similarly careful because of the possibility of Lua throwing memory errors. Any places where a deferred cancellation (or Lua error) could occur when a data structure is in an inconsistent state should have a separate bug reported.

**Comment by daurnimator** [comment] 2015-08-11 03:04
I don't suppose you can use something like `tgkill` with a signal of `0` to poll if the thread still exists?

**Comment by wahern** [comment] 2015-08-11 15:14
PIDs are recycled. So at best it's a heuristic that will appear to work in most situations but is fundamentally broken.

Anyhow, as with the Alpine case, if a thread is being killed asynchronously, trying to join the cqueues thread object should really be the absolute least of your worries.

It did occur to me that we could set a flag before the thread exits. Then we only call pthread_join if we see the flag or we've detected an exit using the robust mutexes (EOWNERDEAD on _trylock).

I'll definitely add that before closing or recategorizing this issue. I won't change the ticket before I merge my autoconf work with the robust mutex detection. (See also https://github.com/wahern/autoguess, for people who have an allergy to autoconf ;)

**Comment by daurnimator** [comment] 2015-08-11 15:17
> PIDs are recycled. So at best it's a heuristic that will appear to work in most situations but is fundamentally broken.

These are TIDs, but yes. It's possibly worthwhile in this case, as we will never have false negatives. (i.e. we are trying to catch an instant where than thread id doesn't exist => if it's been reused, we're no worse off than we already are)

---------------------------------------------------

But yes, robust mutexes seem to be the best solution we can get.

**Comment by wahern** [comment] 2015-08-11 15:21
Ah, I see. So tgkill(getpid(), thread_id) will only send a signal to thread_id if it's in our process. Interesting. But if we take things all the way, then we'd also want to maintain a data structure of all existing threads so we can detect when a thread ID is re-used and mark a pre-existing thread object with that ID as defunct.

I dunno. It still seems like a lot of code and complexity for little benefit.

**Comment by daurnimator** [comment] 2015-08-11 15:23
> But if we take things all the way, then we'd also want to maintain a data structure of all existing threads so we can detect when a thread ID is re-used and mark a pre-existing thread object with that ID as defunct.
> 
> I dunno. It still seems like a lot of code and complexity for little benefit.

I wouldn't bother taking it "all the way".
A simple poll of the TID gives a 80% solution for platforms without robust mutex support.
Any additional effort expended would be better spent campaigning to get those systems to support robust mutexes :P

**Comment by wahern** [comment] 2015-08-11 15:45
All modern Linux/glibc and Solaris systems will have robust mutexes. Neither OS X nor the *BSDs have anything like tgkill, AFAIK.

**Comment by daurnimator** [comment] 2015-08-11 15:50
> Neither OS X nor the *BSDs have anything like tgkill, AFAIK.

I don't have either in front of me right now.... surely they have something that shows TIDs (e.g. for `ps` output?) `tgkill` was just the first that came to mind.

**Comment by wahern** [comment] 2015-08-11 15:59
Most do. See ct_selfid at the bottom of thread.c.

But there's nothing like tgkill, which let's you restrict the thread ID to the current thread group / process. Usually the only way to send signals to a specific thread is by using pthread_kill.

We could dig through the source, but thread implementations varies widely across platforms. For example, FreeBSD, NetBSD, and OpenBSD all implement threading differently.

**Comment by daurnimator** [comment] 2015-08-11 16:09
> Most do. See ct_selfid at the bottom of thread.c.

> But there's nothing like tgkill, which let's you restrict the thread ID to the current thread group / process. 

I meant something to get a list of TIDs in a given process. e.g. for `ps -Teo pid,tid` output.

**Comment by richfelker** [comment] 2015-11-16 03:38
The only solution to this problem is "don't do this" (don't use seccomp on threads). It does not provide you any protection since the target thread can still overwrite any of the process's writable memory, and due to incorrect behavior by the kernel, it violates a critical invariant: that threads control their own lifetimes. Breaking this invariant will definitely cause internal problems in musl libc, for instance the deadlock in the stdio lock.

**Comment by wahern** [comment] 2016-10-19 09:16
Closing as WONTFIX. I agree with Rich that this cannot be satisfactorily solved.

Leaving in the robust mutex support, though, which works (in the sense of maybe providing some useful diagnostic capability) on Linux/glibc and Solaris.

**Closed by wahern** 2016-10-19 09:16 UTC
Labels: bug, component: thread, wontfix
